version: '3.6'
services:
  web:
    image: 'yrzr/gitlab-ce-arm64v8'
    restart: always
    hostname: 'gitlab.cmd.local'
    environment: 
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.cmd.local'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:8000'
      - '443:4443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'